myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "myapp" #naming the app for namespace, so that it can be referenced in the template
urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', views.products, name='products'),
    #path('products/', views.ProductListView.as_view(), name='products'),
    #path('products/<int:id>', views.product_detail, name =  'product_detail'), #the name parameter is to name the url for use in the template
    path('products/<int:pk>', views.ProductDetailView.as_view(), name = 'product_detail'),
    #path('products/add', views.add_products, name='add_products'),
    path('products/add', views.ProductCreateView.as_view(), name='add_products'),
    path('products/update/<int:id>/', views.update_product, name="update_product"),
    path('products/delete/<int:id>/', views.delete_product, name="delete_product"),
    path('products/mylistings', views.my_listings, name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(), name='success'),
    path('failed/', views.PaymentFailedView.as_view(), name = 'failed'),
    path('api/checkout-session/<id>', views.create_checkout_session, name='api_checkout_session'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls'))

]

urlpatterns+= static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = "users" #naming the app for namespace, so that it can be referenced in the template
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/',  authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',  authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>', views.seller_profile, name='sellerprofile'),
]

users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    
    def __str__(self):
        return self.user.username
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to ='profile_pictures')
    contact_number = models.CharField(default='99999', max_length=100)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none', "placeholder":"demo@gmail.com"}))
    username =  forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none', "placeholder":"user1234"}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

users/views.py
from email.policy import default
from multiprocessing import context
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User
from django.contrib import messages


# Create your views here.

def register(request):
    form = NewUserForm
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid:
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'account was created for' + user)
            return redirect('users:login')
   
    context = {'form' : form}
    
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def create_profile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('contact_num')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user = user, image=image, contact_number=contact_number)
        profile.save()
    return render(request, 'users/createprofile.html')

def seller_profile(request, id):
    seller = User.objects.get(id=id)
    
    context= {
        'seller' : seller
    }
    
    return render(request, 'users/sellerprofile.html', context)

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="mb-4">
        <label for="">Upload Profile Image</label>
        <input placeholder="Choose a clear image" type="file" accept="image/*" name="upload" id= "upload" class="py-2" >
    </div>

    <div class="mb-4">
        <label for="">Conatact Number</label>
        <input placeholder="9999999999" type="text" name="contact_num" id= "contact_num" class="shadow appearance-none border rounded py-2 py-3 mr-10" >
    </div>
<input class="bg-green-500 text-white px-5 py-2" name="Add" type="submit" value="Add">
</form>

{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl font-bold m-10">User Login</h1>
<div class="container py-5">
    <form method="post" class="w-2/5 bg-white shadow-lg m-10 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username }}
            </div>
        </div>


        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password }}
            </div>
        </div>
        {{form.errors}}
        <button class="bg-green-500 px-5 py-2 text-white" type="submit">Login</button>

        {% for message in messages %}
        <p id="messages">{{message}}</p>
        {% endfor %}

           
    </form>
    <div class="mb-10 px-10">Do not have an account ? <a class="text-indigo-500" href="{% url 'users:register' %}">Register</a> </div>
    
</div>


{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>You have now been logged out</h1>
{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-8 sm:grid-cols-1">
    <div class="rounded shadow-lg ">
        <div>
            <img src="{{ user.profile.image.url }}" alt="">
        </div>
        <div class="font-bold text-xl px-6 py-4">{{ user.username }}</div>
        <div class="font-bold mb-2 px-6">{{ user.profile.contact_number }}</div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1 class="text-2xl font-bold m-10">User Registeration</h1>
<div class="container py-5">
    <form method="post" class="w-2/5 bg-white shadow-lg m-10 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.username }}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.email }}
            </div>
        </div>


        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password1 }}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{ form.password2 }}
            </div>
        </div>
        {% if form.errors %}
        <p>Your form has errors, please fix</p>
        {%  endif %}
     <button class="bg-green-500 px-5 py-2 text-white" type="submit">Register</button>
           
    </form>

    <div class="mb-10 px-10">Already have an account ? <a class="text-indigo-500" href="{% url 'users:login' %}">Login</a> </div>
</div>


{% endblock %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-8 sm:grid-cols-1">
    <div class="rounded shadow-lg ">
        <div>
            <img src="{{ seller.profile.image.url }}" alt="">
        </div>
        <div class="font-bold text-xl px-6 py-4">{{ seller.username }}</div>
        <div class="font-bold mb-2 px-6">{{ seller.profile.contact_number }}</div>
    </div>
</div>

{% endblock %}